### ISSUE TITLE
dial tcp 127.0.0.1:31000: connect: connection refused

### ISSUE THREAD

**Issue by xteeio** [ContainerSolutions/trow#11]
Suddenly, it shows the following error. Any idea how to fix?

The push refers to repository [trow.kube-public:31000/ubuntu_19.04_custom_v16.0]
Get http://trow.kube-public:31000/v2/: dial tcp 127.0.0.1:31000: connect: connection refused

**Comment by amouat** [comment]
I'll need some more details I'm afraid. In particular, where is k8s running? Is it minikube or Docker for Mac? 

You might be able to just re-run the installation or configure-host script.

**Comment by xteeio** [comment]
im running it on ubuntu. when i re-run the install script, the approving certificate seems to take a very long time, its more than 3 hours now and i am still waiting patiently. Any idea?

**Comment by amouat** [comment]
There's no point in waiting for 3 hours. Sometimes it takes a while, but still under 10 mins.

What environment are you running in - are you using minikube? If so, which version?

**Comment by rajbarua** [comment]
I think I hist the same issue. I am installing trow in a K8s cluster created via Kubespray. The OS is CentOS.

I have 4 worker nodes and one master. When I do "docker push trow.kube-public:31000/test/nginx:alpine" on any of the worker nodes (not master) I get "Get http://trow.kube-public:31000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

In all the worker nodes the trow entry in /etc/hosts is:
127.0.0.1 trow.kube-public # Added by trow install

Does that look right? Should it not be the real IP of the node?

I also executed "configure-host.sh --add-hosts" on the master and noticed that the script was failing to get the IP address of the nodes. I am no expert in scripting but in function "get_ip_from_k8s", line number 14 is returning empty. Upon which the script assumes the IP to be "127.0.0.1"

**Comment by amouat** [comment]
Thanks @rajbarua!

That `/etc/hosts` entry definitely doesn't sound right. Which version of k8s are you using?

I haven't tested via centos, so that could be the problem. I'll try to take a look soon but I have some other pressing work atm.

@xteeio - please let me know what version of k8s you're using as well.

**Comment by rajbarua** [comment]
Thanks @amouat 

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by amouat** [comment]
Ok, I'm a little further. 

There was a problem with entrypoint/cmd settings for the init pod, which meant it was erroring out on certain versions of k8s (I think this is a k8s bug). I've fixed this, but now I'm hitting a problem with pod security policies on microk8s which I want to fix before closing this issue. 

I'm not sure if both of you have the same issue or not at the minute.

**Comment by amouat** [comment]
There seems to be a few different things going on in this issue and I can't help any more without further details.

@rajbarua it is actually correct for the `/etc/hosts` entries on the hosts to point to 127.0.0.1; it's using the nodeport interface. I suggest editing the `/etc/hosts` on the client machine you want to push from to the IP of a worker node in your cluster and seeing if that works. You might also need to open port 31000 in your network for inbound traffic.

@xteeio Because of the 127.0.0.1 reference, I've been assuming you're using microk8s. Unfortunately I've been unable to get Trow working with the current version of microk8s. I'll try again when they upgrade to containerd 1.3.0.

If either of you want further help, please open a new issue with more details and I'll be happy to try and get things going. For the moment I'm closing this issue and opening one microk8s.

**Comment by xteeio** [comment]
Recently  i change my kubernetes deployment using kubespray kubernetes cluster.

I ran the ./install.sh, but endless Approving certificate...

then i ran the kubectl certificate approve trow.kube-public manually, it shows the following:

kube-deploy@oooiio-kube-ceph00:~/Github/trow/install$ kubectl certificate approve trow.kube-public
No resources found
Error from server (NotFound): certificatesigningrequests.certificates.k8s.io "trow.kube-public" not found
kube-deploy@oooiio-kube-ceph00:~/Github/trow/install$ 


kube-deploy@oooiio-kube-ceph00:~/Github/trow/install$ kubectl cluster-info
Kubernetes master is running at https://10.0.97.13:6443
coredns is running at https://10.0.97.13:6443/api/v1/namespaces/kube-system/services/coredns:dns/proxy
kubernetes-dashboard is running at https://10.0.97.13:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
kube-deploy@oooiio-kube-ceph00:~/Github/trow/install$ 

any idea?

**Comment by amouat** [comment]
I guess I need to come up with some diagnostic tools :)

Can you share with me your kubespray config? Then I can just try replicating the issue here.

Can you also issue the following commands:

$ kubectl describe deploy -n kube-public
$ kubectl describe pods -n kube-public
$ kubectl logs -n kube-public trow-deploy-<TAB> -c trow-init

Probably best that we open a new issue for this, but I'm not sure what it is yet.

**Comment by xteeio** [comment]
I use kubespray but all on default config. eg.

[](https://schoolofdevops.github.io/ultimate-kubernetes-bootcamp/cluster_setup_kubespray/)

Here is  the output of the 3 commands:

[](http://202.157.153.177/output.txt)

**Comment by amouat** [comment]
Ok, I didn't realise that kubespray was so complex! Not sure what your cluster is for, but if you're new to k8s, you might want to try kubeone, or a managed solution.

The problem seems to be that DNS isn't working properly in your cluster. The start-up script has stopped here https://github.com/ContainerSolutions/trow/blob/master/install/trow-init-pod/init.sh#L12. That line looks right to me and it works on other clusters. I see you do have CoreDNS running, but I suspect something isn't right.

At this point my only suggestion is I add a time out so that it errors out with a clear message.

**Comment by amouat** [comment]
Hmm, I guess it could also be the kubernetes service wasn't created, but that seems unlikely; you can check with `kubectl describe svc -n kube-public`

**Comment by xteeio** [comment]
you were right. it was dns issue. I had the default cluster name cluster.local changed to something else causing the following line not working. 

trow is working now after i change the cluster name back to cluster.local. Maybe your script should auto detect the cluster name.

`SERVICE_IP=$(dig +short trow.$POD_NAMESPACE.svc.cluster.local`

**Comment by amouat** [comment]
Yes, it should. I'll add that as a new issue. There should also be a better error message.

Thanks for helping me with this!
