### ISSUE TITLE
How to deploy an image with trow being protected with username/password

### ISSUE THREAD

**Issue by CreepDth** [ContainerSolutions/trow#170]
Hi @amouat ,

Hopefully an easy question but I couldnt find it in the docs;
I was able to setup trow with basic username/password protection and we are able to push images to the registry.
However, when I try to deploy them with kubectl, I get an unauthorized, which makes sense.
I've tried to setup a secret for docker setup, which seem to work but I still fail to connect.

Is there any standard to make this work?
greetz,
Remco

**Comment by amouat** [comment]
You should be able to just follow the standard instructions: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

Did you remember to set `imagePullSecrets` on the pod? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

We use this method internally, so it should definitely work. If you still have problems, could you post the YAML you're using?

**Comment by CreepDth** [comment]
Thanks again Adrian, I believe this helped a lot.

One other question; I've noticed that per default the image registry is not persistent. I have created persistent storage, but I am not able to find where I can adjust the default installation to store images on the persistent storage instead.
Can you point me in the right direction?

**Comment by amouat** [comment]
No problem.

Would you like to set-up a quick call to discuss some of this? Just drop an e-mail if so - you should be able to find my address on my profile.

Using persistent storage should be pretty simple and it's what we do in the standard install by default. Depending on your cluster, you should be able to do something like this: https://github.com/ContainerSolutions/trow/blob/master/install/base/stateful-set.yaml#L46-L53 which matches this https://github.com/ContainerSolutions/trow/blob/master/install/base/stateful-set.yaml#L29-L31

To be honest, I think you'd be better served by moving to the standard install and modifying it so that it works for your use case.

**Comment by CreepDth** [comment]
Thanks Adrian I really appreciate your efforts to help me out. I've just checked the links and it makes sense to me. I will review the standard install in the next few weeks and see if I can make this work with our own certs. I will keep you offer for a call on the hold for now, but I might come back to you. So thanks again, have a good weekend!

**Comment by amouat** [comment]
Thanks.

I'm going to close this issue for the minute, but I'll take a note of the issue for improving our docs.

If you hit any problems, please open a new issue for that.

Good luck!

Adrian.
