### ISSUE TITLE
error in yaml formatting for trow.yaml

### ISSUE THREAD

**Issue by chromafunk** [ContainerSolutions/trow#245]
when: 

```kubectl apply -f trow.yaml -n registry```

```error: error parsing trow.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"namespace":interface {}(nil)} ```

**Comment by amouat** [comment]
Right, I need to update the documentation. The problem is the `trow.yaml` file is templated to take the namespace it was installed  in.

Basically you need to run:

 `sed "s/{{namespace}}/*NAMESPACE*/" install/trow.yaml | kubectl apply -f - `

Where *NAMESPACE* is the namespace that trow was installed to.

I'm not really sure why the file was templated like this rather than just passing `-n`. I'll open another issue to look into this.

Apologies for the delay in replying.

**Comment by amouat** [comment]
Yes, thanks for that @etoiledemer
