### ISSUE TITLE
Could not fetch content descriptor

### ISSUE THREAD

**Issue by edersonmf** [ContainerSolutions/trow#30]
Hi,

I have successfully installed trow on my k8s cluster, built an image externally and pushed it to the registry. However, when I try to pull it from the registry I get the error describe below:

Steps to reproduce:

1. Pull nginx image from docker hub `docker pull nginx:alpine`
2. Tag nginx image in order to push it to trow `docker tag nginx:alpine trow.kube-public:31000/test/nginx:alpine`
3. Push image to trow `docker push trow.kube-public:31000/test/nginx`
4. K8s cluster is set up with crio + containerd. So, when it tries to pull the image it fails with an error `/ # crictl pull trow.kube-public:31000/test/nginx:alpine`
`FATA[2019-12-02T20:11:21.562209503Z] pulling image failed: rpc error: code = NotFound desc = failed to pull and unpack image "trow.kube-public:31000/test/nginx:alpine": failed to copy: httpReaderSeeker: failed open: could not fetch content descriptor sha256:222dfec1866c8776195903332dabf058910bff2319f0737aa870781cf83071e6 (application/vnd.docker.distribution.manifest.v2+json) from remote: not found`

I am not sure if this is somehow related to https://github.com/ContainerSolutions/trow/issues/24

**Comment by amouat** [comment]
Hi,

I doubt it's related to #24, but it probably is related to #14. Basically, the quick install won't work with containerd-cri atm.

How did you install the Kubernetes cluster? 

If you have a domain name you can use, your best plan is to install Trow using the standard install and use cert-manager to obtain a TLS cert.

I'll take another look at the quick install and containerd-cri in a few weeks.

**Comment by edersonmf** [comment]
Thanks @amouat!

Quick install does most of the job with containerd-cri. I just added a couple of manual steps like routing trow.kube-public to the right IP address and putting the CA cert at the system level so that containerd could find it.

I have a local dev K8s cluster using k3d+k3s.

This set up is just working fine with the exception of this issue.

Thanks for checking this.

**Comment by amouat** [comment]
Just looking at this again, it might actually be a pull by digest issue, which is something I'm working on currently. I'll update this issue when I've added that feature.

**Comment by amouat** [comment]
Looking at this again, I think the problem was routing (or maybe certificates). Looking at similar errors on-line, it suggests containerd is failing to connect to the registry, not that the registry doesn't have the image.

You mentioned you configured the routing yourself, so I'm wondering if you missed the node/VM that you ran `crictl` from? 

I realise this is an old issue and things have probably changed, so unless you are still hitting this problem or have a simple way to recreate the issue, I'm going to close it. I think it's best to track this in a separate containerd issue (once containerd hits 1.4 I'm hopeful we will be able to modify the quick install to support it).
