### ISSUE TITLE
What is the difference to Harbor?

### ISSUE THREAD

**Issue by estahn** [ContainerSolutions/trow#81]
A colleague of mine sent this to me and I'm trying to understand the value proposition as well as the difference to https://goharbor.io/

**Comment by amouat** [comment]
Hi Enrico,

Do you think it would it be worthwhile if wrote a Hashicorp style vs page? https://www.nomadproject.io/intro/vs/

Harbor builds on-top of Docker Distribution, addresses a very wide range of use cases and supports a bunch of different storage options. Harbor is made up of a large set of services, most of which are described here: https://goharbor.io/docs/1.10/install-config/. Each organisation typically installs a single Harbor instance in a central location that is used by multiple teams and clusters.

By contrast, Trow is designed to be much more lightweight and to run _inside each_ cluster it serves. It also integrates with the cluster itself, for example by controlling which images can run in the cluster through a validating webhook - this allows you to say things like "only allow images from this registry to run or official images from the Docker Hub". In the future one of the areas I really want to develop is advanced distribution, possibly using P2P or similar techniques to transfer images to nodes as quickly as possibly (meaning containers start up faster). 

I hope to actually see Trow working alongside Harbor in some installations. In this case, Harbor would be a central store of all images and would keep a full history the images. Trow would run inside each of the clusters in the organisation and would distribute the working set of images to nodes. Trow would automatically pull images through from Harbor for use in the cluster. There a lot of potential benefits from this approach:

 1) Images can be distributed faster - the Trow registries are local to the cluster which means a shorter network trip - they effectively act as a local cache for the central registry.
 2) Less stress on the central Harbor server, which now only needs to serve the Trow registries, rather than every node.
 3) The individual clusters can configure the registry differently according to their needs, for example a dev cluster may have looser restrictions on where images can come from and how to handle images with vulnerabilities discovered in a scan.

Some of this is dependent on features that are still in development, but hopefully that gives you an idea of the differences/proposition.

**Comment by amouat** [comment]
I'm going to add this to the FAQ and close the issue unless you have any more q's @estahn

**Comment by amouat** [comment]
I've added a [short document](https://github.com/ContainerSolutions/trow/blob/master/docs/COMPARISON.md) on this.
